"""Self-teacher prompt construction for GSM8K.

Templates are copied verbatim from Tufalabs/opsd-predictive-law
(verl/trainer/config/actor/actor.yaml). The conditions themselves are ours: every
privileged context here is derived from the dataset's own reference solution, so
nothing is generated by a model and nothing has to be audited for leakage.

Two families:
  - a dose scale of true information (none -> step1 -> all steps -> full solution)
  - misleading contexts (another problem's solution, or a corrupted one), which
    should push the gap negative
"""
import random
import re

# --- verbatim from the Tufa repo ---------------------------------------------
REPROMPT_TEMPLATE = "{prompt}{solution}{feedback}\n\nCorrectly solve the original question."

SOLUTION_TEMPLATE = "\n\nCorrect solution:\n\n{successful_previous_attempt}"

FEEDBACK_TEMPLATE = (
    "\n\nThe following is feedback from your unsuccessful earlier attempt:\n\n{feedback_raw}"
)

ANSWER_INSTRUCTION = (
    "\n\nSolve the problem step by step. End your reply with the final numeric answer "
    "on its own line, in the form: #### <number>"
)

CONDITIONS = [
    "none",                 # bare prompt: the ruler, plain resampling
    "gold_step1",           # first reasoning step only
    "gold_steps",           # every step but the last: no final number
    "gt_solution",          # full reference solution (ceiling)
    "wrong_solution",       # another problem's solution (misleading)
    "corrupted_solution",   # this problem's solution with the numbers altered
]

MISLEADING = ("wrong_solution", "corrupted_solution")


# --- helpers over the GSM8K `answer` field -----------------------------------

def strip_calc(text):
    """Drop the dataset's calculator annotations: 48/2=<<48/2=24>>24 -> 48/2=24."""
    return re.sub(r"<<[^>]*>>", "", text)


def split_solution(answer):
    """Return (reasoning steps, final answer string) from a GSM8K answer field."""
    body = strip_calc(answer).strip()
    lines = [l.strip() for l in body.split("\n") if l.strip()]
    final = ""
    if lines and lines[-1].startswith("####"):
        final = lines[-1]
        lines = lines[:-1]
    return lines, final


def gold_prefix(answer, n_steps=None):
    """The first n_steps reasoning steps, with no final answer. None means all."""
    steps, _ = split_solution(answer)
    if n_steps is not None:
        steps = steps[:n_steps]
    return "\n".join(steps)


def full_solution(answer):
    steps, final = split_solution(answer)
    return "\n".join(steps + ([final] if final else []))


def corrupt(answer, seed=0):
    """Same solution, wrong numbers. Every computed result is shifted by the same
    delta, and later mentions of a shifted value are rewritten too, so the text
    stays internally consistent: the only way to catch it is to redo the
    arithmetic."""
    rng = random.Random(seed)
    delta = rng.choice([-3, -2, -1, 1, 2, 3])
    text = full_solution(answer)

    def as_str(val):
        return str(int(val)) if float(val).is_integer() else ("%.2f" % val)

    # results are the numbers right after '=' or after the '####' marker
    results = []
    for m in re.finditer(r"(?:=\s*\$?|####\s*\$?)(-?[\d,]*\.?\d+)", text):
        try:
            results.append(float(m.group(1).replace(",", "")))
        except ValueError:
            pass

    mapping = {}
    for val in results:
        new = val + delta
        if new <= 0:
            new = val + abs(delta)
        mapping[as_str(val)] = as_str(new)

    if not mapping:
        return text
    # rewrite every occurrence, so a result reused in a later step stays consistent
    pattern = re.compile(r"(?<![\d.])(%s)(?![\d.])" % "|".join(
        re.escape(k) for k in sorted(mapping, key=len, reverse=True)))
    return pattern.sub(lambda m: mapping[m.group(1)], text)


def context_answer(text):
    """The final number a privileged context points at, if any. Used to measure
    how often the model just copies the context instead of solving."""
    m = re.findall(r"####\s*\$?(-?[\d,]*\.?\d+)", text)
    if not m:
        return None
    try:
        return float(m[-1].replace(",", ""))
    except ValueError:
        return None


# --- prompts -----------------------------------------------------------------

def student_prompt(question):
    return question + ANSWER_INSTRUCTION


def build_context(condition, answer, other_answer=None, seed=0):
    """The privileged text for this condition, or None when there is none."""
    if condition == "none":
        return None
    if condition == "gold_step1":
        return gold_prefix(answer, 1) or None
    if condition == "gold_steps":
        # every step but the last, so the final number is genuinely withheld:
        # GSM8K's last step usually states it inline ("48+24 = 72")
        steps, _ = split_solution(answer)
        return "\n".join(steps[:-1]) or None
    if condition == "gt_solution":
        return full_solution(answer) or None
    if condition == "wrong_solution":
        return full_solution(other_answer) if other_answer else None
    if condition == "corrupted_solution":
        return corrupt(answer, seed=seed) or None
    raise ValueError("unknown condition: %s" % condition)


def teacher_prompt(condition, question, context):
    """Falls back to the bare student prompt when there is no context, mirroring
    Tufa's gating (mask False means no signal)."""
    base = student_prompt(question)
    if not context:
        return base
    return REPROMPT_TEMPLATE.format(
        prompt=base,
        solution=SOLUTION_TEMPLATE.format(successful_previous_attempt=context),
        feedback="")
